### ISSUE TITLE
Kali2 mingw32 logic test fails

### ISSUE THREAD

**Issue by breakersall** [CroweCybersecurity/ps1encode#6]
When using ps1encode in Kali2 without required mingw32 dependency, logic test for it being installed passes and it says final_.exe is created with no exe. This is an issue if you are a dumb user like myself who forgets to install dependencies and then cannot find my shiny new Trojan named final_.exe that wasn't created.

Example log:
root@kali:/tmp# ruby ps1encode.rb -i IP-REMOVED -p 443 -t exe
No platform was selected, choosing Msf::Module::Platform::Windows from the payload
No Arch selected, selecting Arch: x86 from the payload
No encoder or badchars specified, outputting raw payload
Payload size: 347 bytes

compiling...
final_.exe created!
root@kali:/tmp# ls
file85Wsk9
ps1encode.rb
ssh-2xDtZUX4btJ4
systemd-private-90c7838a76be4338a5f23722e37c4db4-colord.service-zipEzF
systemd-private-90c7838a76be4338a5f23722e37c4db4-rtkit-daemon.service-Hyiaqe
tracker-extract-files.0
VMwareDnD
vmware-root
root@kali:/tmp# ls -la
total 68
drwxrwxrwt 13 root root  4096 Jan 25 13:40 .
drwxr-xr-x 25 root root  4096 Jan 11 09:49 ..
-rw-r--r--  1 root root     0 Jan 22 15:03 file85Wsk9
drwxrwxrwt  2 root root  4096 Jan 22 14:48 .font-unix
drwxrwxrwt  2 root root  4096 Jan 22 14:49 .ICE-unix
-rwxr-xr-x  1 root root 10947 Jan 25 13:39 ps1encode.rb
drwx------  2 root root  4096 Jan 22 14:49 ssh-2xDtZUX4btJ4
drwx------  3 root root  4096 Jan 22 14:48 systemd-private-90c7838a76be4338a5f23722e37c4db4-colord.service-zipEzF
drwx------  3 root root  4096 Jan 22 14:48 systemd-private-90c7838a76be4338a5f23722e37c4db4-rtkit-daemon.service-Hyiaqe
drwxrwxrwt  2 root root  4096 Jan 22 14:48 .Test-unix
drwx------  2 root root  4096 Jan 22 14:49 tracker-extract-files.0
drwxrwxrwt  2 root root  4096 Jan 22 14:48 VMwareDnD
drwx------  2 root root  4096 Jan 22 14:49 vmware-root
-r--r--r--  1 root root    11 Jan 22 14:48 .X0-lock
drwxrwxrwt  2 root root  4096 Jan 22 14:48 .X11-unix
drwxrwxrwt  2 root root  4096 Jan 22 14:48 .XIM-unix
root@kali:/# locate final_.exe
root@kali:/# cd .

**Comment by addenial** [comment]
fixed in the latest update.
